services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: nutritrack
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nutritrack_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app   # map entire project for Flask & Gunicorn
    depends_on:
      - db
    command: bash -c "flask db upgrade && gunicorn wsgi:app --bind 0.0.0.0:5000 --workers 3"

volumes:
  db_data:
