"""Added BMI, Activity Level and Maintenance Calories to users table

Revision ID: 0be3a50ddb3a
Revises: 
Create Date: 2025-10-31 19:02:06.367272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be3a50ddb3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bmi', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('maintenance_calories', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('maintenance_calories')
        batch_op.drop_column('bmi')
        batch_op.drop_column('activity_level')

    # ### end Alembic commands ###
