"""Updated the values

Revision ID: 698f41e1fda8
Revises: a62a9c636e0d
Create Date: 2025-11-05 14:31:41.847684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698f41e1fda8'
down_revision = 'a62a9c636e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('protein',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('carbs',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('fats',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('fibers',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('iron',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('calcium',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('vitamin_c',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('sodium',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
        batch_op.alter_column('potassium',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('potassium',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('sodium',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('vitamin_c',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('calcium',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('iron',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('fibers',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('fats',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('carbs',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('protein',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
