"""Added Indian foods table to database

Revision ID: 700560f794a4
Revises: 0be3a50ddb3a
Create Date: 2025-10-31 19:31:04.324458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700560f794a4'
down_revision = '0be3a50ddb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indian_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True))
        batch_op.alter_column('food_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('food_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indian_foods', schema=None) as batch_op:
        batch_op.alter_column('food_name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('food_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
