"""Updated User Meal Log and Meal Entry

Revision ID: 7c50c597722b
Revises: ebbf96e04d6a
Create Date: 2025-11-04 12:58:27.618531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c50c597722b'
down_revision = 'ebbf96e04d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fibre', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('iron', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('calcium', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('vitc', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sodium', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('potassium', sa.Float(), nullable=False))
        batch_op.drop_column('tota_calories')

    with op.batch_alter_table('user_meal_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_calories', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_protein', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_carbs', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_fat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_fibre', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_iron', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_calcium', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_vitc', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_sodium', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_potassium', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meal_log', schema=None) as batch_op:
        batch_op.drop_column('total_potassium')
        batch_op.drop_column('total_sodium')
        batch_op.drop_column('total_vitc')
        batch_op.drop_column('total_calcium')
        batch_op.drop_column('total_iron')
        batch_op.drop_column('total_fibre')
        batch_op.drop_column('total_fat')
        batch_op.drop_column('total_carbs')
        batch_op.drop_column('total_protein')
        batch_op.drop_column('total_calories')

    with op.batch_alter_table('meal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tota_calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('potassium')
        batch_op.drop_column('sodium')
        batch_op.drop_column('vitc')
        batch_op.drop_column('calcium')
        batch_op.drop_column('iron')
        batch_op.drop_column('fibre')
        batch_op.drop_column('fat')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')
        batch_op.drop_column('calories')

    # ### end Alembic commands ###
