"""Added maintenance values for nutrients

Revision ID: a62a9c636e0d
Revises: 7c50c597722b
Create Date: 2025-11-05 13:37:48.873672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62a9c636e0d'
down_revision = '7c50c597722b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fats', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fibers', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('iron', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('calcium', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('vitamin_c', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('potassium', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('potassium')
        batch_op.drop_column('sodium')
        batch_op.drop_column('vitamin_c')
        batch_op.drop_column('calcium')
        batch_op.drop_column('iron')
        batch_op.drop_column('fibers')
        batch_op.drop_column('fats')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')

    # ### end Alembic commands ###
