"""Added Indian foods

Revision ID: ebbf96e04d6a
Revises: 700560f794a4
Create Date: 2025-10-31 19:56:01.705638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbf96e04d6a'
down_revision = '700560f794a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indian_foods', schema=None) as batch_op:
        batch_op.alter_column('food_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('food_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indian_foods', schema=None) as batch_op:
        batch_op.alter_column('food_name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('food_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
